spring:
  application:
    name: rjst-backend-service
  datasource:
    url: jdbc:postgresql://backend:5432/backend
    username: backend
    password: backend
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: public
    enabled: false
    change-log: classpath:changelog.yaml
    show-summary: off
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    use-root-path: true
