spring:
  application:
    name: rjst-backend-service
  datasource:
    url: jdbc:postgresql://backend:5432/backend
    username: backend
    password: backend
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      allow-pool-suspension: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: public
    enabled: false
    change-log: classpath:changelog.yaml
    show-summary: off
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://authentik.rjst.de/application/o/rjst-backend-service/
      client:
        registration:
          authentik:
            scope: openid,profile,email,roles
            authorizationGrantType: authorization_code
        provider:
          authentik:
            issuer-uri: https://authentik.rjst.de/application/o/rjst-backend-service/

management:
  server:
    port: 80

springdoc:
  swagger-ui:
    use-root-path: true
