-- liquibase formatted sql

-- changeset rober:1731362736100-1
    CREATE TABLE player
    (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name          VARCHAR(255),
        password      VARCHAR(255),
        process_state VARCHAR(255),
        pod           VARCHAR(255),
        thread        VARCHAR(255),
        balance       DECIMAL,
        created       TIMESTAMP WITHOUT TIME ZONE,
        updated       TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_player PRIMARY KEY (id)
    );

