apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot.fullname" . }}-cfg
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      data:
        redis:
          host: vpn.rjst.de
          port: 6379
      datasource:
        url: jdbc:postgresql://vpn.rjst.de:5432/backend
        hikari:
          minimum-idle: 1
      jpa:
        hibernate:
          ddl-auto: none
        open-in-view: false
      liquibase:
        default-schema: public
        enabled: true
        change-log: classpath:changelog.yaml
      kafka:
        bootstrap-servers: kafka.kafka.svc.cluster.local:9092
        consumer:
          group-id: test
    security:
      ldap:
        url: ldap://vpn.rjst.de:389
        username: "trjstbackend"
        password: "123"
    springdoc:
      swagger-ui:
        use-root-path: true
    management:
      zipkin:
        tracing:
          endpoint: http://jaeger-collector.istio-system.svc:9411/api/v2/spans
      tracing:
        sampling:
          probability: 1.0
