apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot.fullname" . }}-cfg
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://vpn.rjst.de:5432/backend
        hikari:
          minimum-idle: 1
      jpa:
        hibernate:
          ddl-auto: none
        open-in-view: false
      liquibase:
        default-schema: public
        enabled: true
        change-log: classpath:changelog.yaml
        show-summary: off
      cloud:
        openfeign:
          client:
            config:
              ipQuery:
                url: https://api.ipquery.io
              finance:
                url: https://finance-batch.vpn.rjst.de
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://authentik.rjst.de/application/o/rjst-backend-service/
          client:
            registration:
              authentik:
                scope: openid,profile,email,roles
                authorizationGrantType: authorization_code
            provider:
              authentik:
                issuer-uri: https://authentik.rjst.de/application/o/rjst-backend-service/
      threads:
        virtual:
          enabled: true
    springdoc:
      swagger-ui:
        use-root-path: true
