apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot.fullname" . }}-cfg
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://vpn.rjst.de:5432/backend
        hikari:
          minimum-idle: 1
      jpa:
        hibernate:
          ddl-auto: none
        open-in-view: false
      boot:
        admin:
          client:
            url: http://rjst-spring-boot-admin.dev.svc.cluster.local
            instance:
              service-base-url: https://rjst-backend-service.rjst.de
              management-base-url: http://rjst-backend-service.dev.svc.cluster.local:8081
              name: rjst-backend-service
      ldap:
        base: dc=rjst,dc=de
        urls: ldap://vpn.rjst.de:389
        username: cn=trjstbackend,ou=tool,ou=users,dc=rjst,dc=de
        password: "123"
    security:
      tool-user: "trjstbackend"
    springdoc:
      swagger-ui:
        use-root-path: true
